### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by JervNorsk** [Josiah-Kunz/Gene-Hunter#2]
Hello, do you need collaborators? 

I'm pretty new with Unreal Engine, I'm searching for a project to learn together.

**Comment by Josiah-Kunz** [comment]
Hello Jerv! Let's chat via email: AskGeneHunter@gmail.com

The short answer, though, is that I'm not _quite_ ready for collaborators. I would minimally like the battle engine done before embarking on group work. I find that when a Pokemon-like game is publicized, it fizzles out. Sometimes, this is because of over-hype and a weak foundation. 

I would like the foundation to be solid before collaborating with other talented people. This sends the message that I'm serious and I've thought about it.

Frankly, there would be little for you to work on right now. When it is time to collaborate, though, you'll be at the top of my list!
